spring:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev

  application:
    name: app_corretores

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: caches